functions:
  controller:
    handler: ./controller
    image: boilfish/controller:1.0.4
    lang: controller
  func0:
    handler: ./func0
    image: boilfish/func0:1.0.4
    lang: worker
  func1:
    handler: ./func1
    image: boilfish/func1:1.0.4
    lang: worker
  func2:
    handler: ./func2
    image: boilfish/func2:1.0.4
    lang: worker
  func3:
    handler: ./func3
    image: boilfish/func3:1.0.4
    lang: worker
  func4:
    handler: ./func4
    image: boilfish/func4:1.0.4
    lang: worker
  func5:
    handler: ./func5
    image: boilfish/func5:1.0.4
    lang: worker
provider:
  gateway: 127.0.0.1:31112
  name: openfaas
version: '1.0'
