version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  func0:
    lang: python3-onnx
    handler: ./func0
    image: boilfish/func0:latest

  func1:
    lang: python3-onnx
    handler: ./func1
    image: boilfish/func1:latest

  func2:
    lang: python3-onnx
    handler: ./func2
    image: boilfish/func2:latest

  func3:
    lang: python3-onnx
    handler: ./func3
    image: boilfish/func3:latest

  func4:
    lang: python3-onnx
    handler: ./func4
    image: boilfish/func4:latest

  funcrq:
    lang: python3-onnx
    handler: ./funcrq
    image: boilfish/funcrq:latest

