version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  fun1:
    lang: python3
    handler: ./fun1
    image: boilfish/func1:1.0.0
  func3:
    lang: python3-onnx
    handler: ./func3
    image: boilfish/func3:1.1.5