version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  func0:
    lang: worker
    handler: ./func0
    image: boilfish/func0:1.0.2

  func1:
    lang: worker
    handler: ./func1
    image: boilfish/func1:1.0.2

  func2:
    lang: worker
    handler: ./func2
    image: boilfish/func2:1.0.2

  func3:
    lang: worker
    handler: ./func3
    image: boilfish/func3:1.0.2

  func4:
    lang: worker
    handler: ./func4
    image: boilfish/func4:1.0.2

  func5:
    lang: worker
    handler: ./func5
    image: boilfish/func5:1.0.2

  controller:
    lang: controller
    handler: ./controller
    image: boilfish/controller:1.0.2